apiVersion: apps/v1
kind: Deployment
metadata:
  name: heimdall
  labels:
    app: heimdall
spec:
  selector:
    matchLabels:
      app: heimdall
  replicas: 10
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: heimdall
    spec:
      containers:
        - name: heimdall
          image: ghcr.io/linuxserver/heimdall
          imagePullPolicy: Always
          env:
          - name: PUID
            valueFrom:
              configMapKeyRef:
                name: homelab-config
                key: puid
          - name: PGID
            valueFrom:
              configMapKeyRef:
                name: homelab-config
                key: pgid
          - name: TZ
            valueFrom:
              configMapKeyRef:
                name: homelab-config
                key: tz
          volumeMounts:
            - mountPath: /config
              name: config
          resources:
            requests:
              cpu: 100m
              memory: "600Mi"
            limits:
              cpu: 150m
              memory: "800Mi"
          readinessProbe:
            httpGet:
              port: 80
              path: /index.php
            initialDelaySeconds: 0
            periodSeconds: 1
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 1
          livenessProbe:
            httpGet:
              path: /index.php
              port: 80
            initialDelaySeconds: 1
            periodSeconds: 1
      volumes:
        - name: heimdall-volume
          #to finish
