apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: homelab-ingress
spec:
  rules:
    - host: heimdall.yggdrasilnetwork.com
      http:
        paths:
          - path: /
            backend:
              serviceName: heimdall
              servicePort: 80