apiVersion: v1
kind: Service
metadata:
  name: blue-green
spec:
  selector:
    app: blue-green
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
